//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> SizeMaxDiscount { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public Nullable<int> CurrentDiscount { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MaxDiscount MaxDiscount { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Сategory Сategory { get; set; }
    }
}
